### ISSUE TITLE
Tracking temperature, heater usage, other energy related stats

### ISSUE THREAD

**Issue by rct** [gazoodle/geckolib#8] opened 2020-11-17 17:04 UTC
I'd like to track/log/plot the changes in temperature. If possible, I'd also like to track how often and how long the heater runs(*).  Is anyone doing anything along these lines yet?

I've seen mentions of people working on Home Assistant integration. Anyone have pointers to repos where that work is occurring?

I know it is going to take a while to work everything out. I'm hoping to just get something quick and dirty done that publishes data to MQTT that I can use in Home Assistant or other environments (Influx/Grafana, etc.)

Anyone work out how quickly your spa loses heat at various outdoor temperatures? 

(*) I'm interested in having some idea of energy consumption. I know I need to get and install some energy monitoring for branch circuits like the spa, but I haven't worked out a plan yet. If anyone has any suggestions I'd love to hear what you've done.

**Comment by gazoodle** [comment] 2020-11-17 17:34
Almost exactly why I started this project in the first place! I'm most of the way through a Home Assistant integration to help with this and I'll keep this thread updated as it goes.

I'm planning on wrapping a current transformer round the SPA line too ... there are several devices that support this and can integrate into HA ... Shelly and Sonoff do some great devices that can monitor energy consumption and Theo Arends' great Tasmota (https://tasmota.github.io/docs/) project or ESPHome (https://esphome.io/) are both things that might help here too ... I've been replacing the firmware in my ESP8266 based switches and devices for quite a while now.

**Comment by agittins** [comment] 2020-11-18 06:53
Same! As I don't have an in.touch wireless thingie I'm hoping to integrate directly with the controller, but I am hopeful that this library will provide the bones for that, as I'm assuming they are simply taking the control bus messages and sending them over the wireless link.

I'd like to use this library in an esp8266 running esphome, and natively expose whatever's possible directly to home assistant that way. There are many challenges to win before that happens, though!

And just in case that wasn't nerdy enough....

I haven't worked out temp loss vs ambient, but what I have worked out is that our 1000L tub:
- loses 4 degrees C per 24 hours or 1 degree per 6 hours (measured as 39 to 31 deg over two days with ambient ~21deg C)
- (math) our 4KW heater should take 334 minutes to raise 1000L by 19 degrees, so about 29 minutes per degree C.
- (observed) it heats at about 2 degrees per hour (yay! math checks out!)
- therefore, heater runs 2 hours a day to counteract the 4 degrees daily heat loss. 4KW x 2 hours = 8KW/h/day = $2.70/day for us.
- also, heating up from 21c ambient to 39c takes 9 hours and costs $12.24

So... if we're going to use it within 4 days, we're better off leaving it on (for spontaneous availability), otherwise cheaper to turn it down until needed (assuming one knows 9 hours in advance!).

Of course these are all rough approximations, automating this will give much better data, obviously!

**Comment by gazoodle** [comment] 2020-12-13 10:25
> Same! As I don't have an in.touch wireless thingie I'm hoping to integrate directly with the controller, but I am hopeful that this library will provide the bones for that, as I'm assuming they are simply taking the control bus messages and sending them over the wireless link.

Elsewhere I've seen someone mention that the spa pack and in.touch2 devices use RS485, so that ought to be fairly straightforward to work out. During lockdown, I replaced a faulty in.XM pack with an in.XM2 pack and in.touch2 module, and I still have the old in.XM pack in the garage ... I'll try to power it up and see what comes out of the CO port. I think I have an RS485 module somewhere around.

Also, most of the functionality for this thread ought to be present in the library (0.3.12) now, so I'm closing this issue. Please feel free to reopen if you need to.

**Closed by gazoodle** 2020-12-13 10:25 UTC

**Comment by agittins** [comment] 2021-06-29 10:12
@gazoodle any chance you might be able to pull out your old in.XM pack and take some hi-res photos of the front and back of the board, in particular around the "CO" and "C" ports?

I finally got around to hooking into the connectors on our in.XM2 the other night and tried to work out what was going on comms-wise. I found the IR signal, GND and 12v, and a few options for 5v lines, and on the C port found what looks like a data line and an "enable" line, but that's about it so far. The data line looks like TTL rather than RS485, but it might be only for the display/keypad. I have a feeling an RS485 device might need to signal something at startup or by tying a line low before the pack talks to it. If I could look at your circuit board maybe I could trace out what the pinouts are which will give me a boost along.

If I can't get full comms going, at least I might be able to work out a read-only status from the keypad/display comms, and send commands to the pack using IR like a remote control. But it would be much nicer to get full two-way comms going if possible. I'd open up our pack but I really don't want to be messing around with a 30A mains circuit!

**Comment by gazoodle** [comment] 2021-07-08 11:03
Just got around to taking the old in.XM pack apart and I have to say there's not a whole lot of useful stuff that I think is available. The circuit board is covered with paint front and back and so it's pretty much impossible to see where the wiring from the CO port and C1/C2 ports are. I suppose one could bung a meter on them and see where they go, but given the profusion of SM passives around the area, I'd not put much hope on giving a definitive connection schedule. Also they have obscured all the chip identifications too so it's nigh on impossible to determine what they are. The MCU is obvious given it's 4 sided pin config and you can sort of imply relay drivers from their proximity to the low and high power relays on the board, but I think it's going to have to be a power-it-up and probe it. I do think that the control ports are all low voltage though. I'll post some pictures too so you can see what I mean!

**Comment by gazoodle** [comment] 2021-07-08 11:07
![image7](https://user-images.githubusercontent.com/47351872/124911688-f459de80-dfe4-11eb-8ede-88ba3aa1b533.jpeg)
![image9](https://user-images.githubusercontent.com/47351872/124911692-f58b0b80-dfe4-11eb-9fa0-bd1643574c08.jpeg)
![image5](https://user-images.githubusercontent.com/47351872/124911696-f754cf00-dfe4-11eb-8af9-4db960cbffb6.jpeg)
![image4](https://user-images.githubusercontent.com/47351872/124911699-f91e9280-dfe4-11eb-99b9-be3b4edd572f.jpeg)
![image3](https://user-images.githubusercontent.com/47351872/124911704-fa4fbf80-dfe4-11eb-9236-48b06e7f477a.jpeg)
![image2](https://user-images.githubusercontent.com/47351872/124911716-fc198300-dfe4-11eb-91ed-6cbc047542be.jpeg)
![image0](https://user-images.githubusercontent.com/47351872/124911722-fd4ab000-dfe4-11eb-8853-c882cc212a8d.jpeg)

**Comment by agittins** [comment] 2021-07-08 17:52
@gazoodle awesome, thank you!

You're not wrong about the conformal coating, it does make things a lot harder! :-) 

If you have any luck scraping the coating off one of the 14-pin chips next to those ports that might be a big help, but the stuff might not be very co-operative! Likewise if you could remove the shroud from around the pins of one of the other connectors like you did for the CO port that might be helpful (not very, but maybe a bit).

A couple of observations off the cuff that might be interesting...

- That white chip near the L1 connector (U9/U10) is an opto-isolated triac. I'm guessing it's used to switch the light? Only needs 5mA to trigger the triac  so easy for an mcu to drive.
- The ports I/O, C, and R/h all have some sort of line driver on them. I was expecting to see Maxim MAX485's or something (it isn't, they're 8pin devices, these are 14pin). Due to discoveries (below) I am wondering if these might be simple line drivers, like 74xx125 quad gate drivers.
- CO port has no line driver on it. This is sort of interesting, as in the techbook for these when they talk about using the in.stik (their field-programming keyfob thingie) it specifically warns about not connecting it while the unit is powered on, and damage caused by doing so would not be covered by warranty. They don't say this about any of the other accessories like keypads, so it does make it sound like the CO port is connected pretty directly to the cpu. It looks that way, too - you can see traces coming directly from the mcu right up to that port, along with a pair of (transistors?) in the way. I wouldn't be surprised if we had a direct SPI interface to the mcu there, or maybe some other programming connection depending on what the mcu is (I had a look and couldn't find any likey mcu's to match - 16MHz clock, 64-pin, with the xtal connections on the side near pins 58/59 - the zigbee versions of the atmega128 might match but they seem pretty unlikely!). 

I spent some time a few weeks ago standing out in the cold at 3am prodding ours with a scope, and I found some things of interest. I messed with the CO port first, which didn't give me very much of interest, although if I recall correctly, it seemed to have the IR receiver signal on pin 5, and I was seeing a really weak comms-like signal on the same pin, but I think it was leaking from elsewhere. It seemed that pin8 was likely GND, pin6 12v, and I was seeing 5v on most of the other pins but as I wasn't drawing any current I couldn't tell if any was VCC or just pull-ups.

I moved to the spare C (keypad) port, this was a bit more interesting. The pins looked much the same as on CO, but pin7 was 0v (so I think perhaps the other keypad was pulling it low, perhaps to indicate that "a device is here, and it wants to talk via serial" which would be consistent with how they described their uart selection in the patent doc).

Pin 3 appeared to be data. About every 20ms, a series of bytes seemed to be transmitted. It looked like 8 bits, 120us per byte, 40us between bytes.

Pin 1 looked like maybe it's a "data active" line or something - it seems to go high for the duration of each block of bytes that are transmitted.

I'm numbering the pins in the standard IDC way, which seems to agree with the photos you've posted, so looking at the front of the unit, pin1 is lower-left, pin2 is upper-left and so on.

Now for some speculation...

I was surprised to see only 0v and 5v on the data lines. I expected either RS232 (10v or more spikey peaks) or RS485 (differential signals, a pair of pins that alternate between values) or something like i2c or SPI (a data line and a clock line). But it looks like maybe we've got a simple two-wire protocol where perhaps an endpoint asserts pin1 to "take control" of the bus, then outputs it's data on pin3, then drops pin1. Maybe. At least for the keypad connectors.

It might be that a more comprehensive interface is available on the CO port, and this might be what the in.touch uses. Or maybe if you pull down pin7 it will give the same interface as the C ports (but this seems maybe unlikely since the CO port doesn't have one of those driver chips, whatever they are).

I expect that the data I'm seeing is the back-and-forth between the controller and the keypad, which if I can read it, will tell me all I want to know, and if I can write to it, would give me the control I want (which may or may not be in line with the structures in this library - I'm hoping they are). Failing that, if I can read what the keypad sees, I can then use the IR port to inject commands, so I could still have functional two-way comms with the unit. Lots of "if's" there.

I think my next step (when I get time) might be to alter my jig so I can intercept the existing keypad's connection, and verify if data happens in both directions on pins 1/3, or if I was only seeing half the conversation and perhaps there's activity on pins 2/4 as well. Then might be to take the plunge and actually connect an esp8266 to the data lines and see if I can get it to recognise any data from the stream :-)

**Comment by agittins** [comment] 2025-06-19 18:46
For those arriving via google and looking for info on hacking the controller pack's keypad and in.touch protocols (versus the network-side of in.touch which this project implements), work is on-going at esphome/feature-requests/issues/2893
